version: 0.2

phases:
  pre_build:
    commands:
      - java -version
      - alternatives --set java /usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64/jre/bin/java
      - java -version
      - ls -lah /usr/lib/jvm
      - echo $JAVA_HOME
      - export JAVA_HOME=/usr/lib/jvm/java-1.8.0-amazon-corretto.x86_64
      - echo $JAVA_HOME
      - echo $PATH
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/helloworld-0.0.1-SNAPSHOT.jar
