version: 0.2

phases:
  pre_build:
    commands:
      - /usr/sbin/alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
      - java -version
      - echo $JAVA_HOME
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/helloworld-0.0.1-SNAPSHOT.jar
