spring:
    application:
        name: hello-world
    main:
        banner-mode: "OFF"
    datasource:
        driver-class-name: org.postgresql.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            maximumPoolSize: 30
            poolName: hello-world
            minimumIdle: 5

server:
    port: 8000