spring:
  datasource:
    url: "jdbc:postgresql://helloworld.database.lan:5432/postgres?currentSchema=hello_world"
    username: postgres
    password:

logging:
  config: classpath:logback-aws.xml

logback.access:
  config: classpath:logback-access-aws.xml