spring:
  datasource:
    url: "jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?currentSchema=hello_world"
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

logging:
  config: classpath:logback-aws.xml

logback.access:
  config: classpath:logback-access-aws.xml
